name: Build & Push PHP Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'php*'

env:
  IMAGE_NAME: skorlok/php

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles_json: ${{ steps.set.outputs.dockerfiles_json }}
    steps:
      - uses: actions/checkout@v4

      - id: set
        run: |
          files=$(ls php* 2>/dev/null || true)
          files_json=$(echo $files | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')
          echo "dockerfiles_json=$files_json" >> $GITHUB_OUTPUT

  build:
    needs: detect
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJSON(needs.detect.outputs.dockerfiles_json) }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skorlok/${{ env.IMAGE_NAME }}:latest
